name: miqc-py
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - numpy
  - pandas
  - anndata
  - scanpy
  - scikit-learn
  - scipy
  - jupyterlab
  - pip
  - pip:
    - stepmix
    - pyro-ppl
    - scvi-tools
    - altair